create database banglore;
use banglore;
create table metro(
owner varchar(25),
metro_number int,
color varchar(25),
start_point varchar(25),
end_point varchar(25),
timimgs varchar(25),
arrival_time varchar(25),
station_name varchar(25),
number_of_coaches int,
number_of_tracks int
);

select*from metro;
insert into metro values('BMRCL',832,'Purple','AGRAHARA','MYSORE ROAD','6:00','5 min','CHICKPETE',6,2);
insert into metro values('BMRCL',842,'Green','NAGSANDRA','SILK INSTITUTE','6:00','7 min','YASHWANTHPUR',6,2);
insert into metro values('BMRCL',743,'Purple','AGRAHARA','MYSORE ROAD','6:00','5 min','RAJAJINAGAR',6,2);
insert into metro values('BMRCL',841,'Purple','AGRAHARA','MYSORE ROAD','6:00','10 min','INDRANAGAR',6,2);
insert into metro values('BMRCL',865,'Green','NAGSANDRA','SILK INSTITUTE','6:00','7 min','KUVEMPU ROAD',6,2);
insert into metro values('BMRCL',863,'Purple','AGRAHARA','MYSORE ROAD','6:00','5 min','CUBBON PARK',6,2);
insert into metro values('BMRCL',976,'Green','NAGSANDRA','SILK INSTITUTE','6:00','5 min','MAHALAKSHMI',6,2);
insert into metro values('BMRCL',953,'Green','NAGSANDRA','SILK INSTITUTE','6:00','10 min','PEENYA',6,2);
insert into metro values('BMRCL',653,'Purple','AGRAHARA','MYSORE ROAD','6:00','10 min','TRINITY',6,2);
insert into metro values('BMRCL',625,'Green','NAGSANDRA','SILK INSTITUTE','6:00','7 min','DASRALLI',6,2);

CREATE TABLE MOVIE(
MOVIE_NAME VARCHAR(25),
HERO_NAME VARCHAR(25),
MOVIE_LANGUAGE VARCHAR(25),
YEAR_OF_RELEASE INT,
RATINGS FLOAT,
DIRECTOR_NAME VARCHAR(25),
MOVIE_BUDGET VARCHAR(25),
MOVIE_TYPE VARCHAR(25),
MOVIE_REVIEW VARCHAR(25),
MOVIE_PLATFORM VARCHAR(25)
);

SELECT *FROM MOVIE;
INSERT INTO MOVIE VALUE('SSE','RAKSHITH SHETTY','KANNADA',2023,9.8,'RAKSHITH','25 CRORES','LOVE','EXCELLENT','AMAZON');
INSERT INTO MOVIE VALUE('TAGARU PALYA','NAGBUSHAN','KANNADA',2023,8.9,'DANANJYA','5 CRORES','ENTAINTEMENT','GOOD','NETFLIX');
INSERT INTO MOVIE VALUE('PAILWAN','KICCHA SUDEEP','KANNADA',2020,9.0,'S KRISHNA','15 CRORES','SPORTS MASALA FILM','EXCELLENT','PRIME');
INSERT INTO MOVIE VALUE('BULL- BULL','DARSHAN','KANNADA',2013,9.2,'M D SRIDHAR','10 CRORES','FRIENDS/LOVE','SUPER','YOU TUBE');
INSERT INTO MOVIE VALUE('UGRAM','SHREE MURULI','KANNADA',2014,9.8,'PRASHANTH NEEL','20 CRORES','THRILLER','EXCELLENT','YOU TUBE');
INSERT INTO MOVIE VALUE('GOOGLY','YASH','KANNADA',2013,10.0,'PAWAN WADEYAR','18 CRORES','ROMANTIC COMEDY','FANTASTIC','PRIME');
INSERT INTO MOVIE VALUE('JOTHE JOTHEYALI','PREM','KANNADA',2006,8.5,'DINAKAR THOOGUDEEPA','10 CRORES','LOVE','VERY GOOD','JIO CENEMA');
INSERT INTO MOVIE VALUE('BAHUBALI2','PRABAS','TELUGE',2017,8.2,'RAJAMOULI','50 CRORES','ACTION','EXCELLENT','NETFLIX');
INSERT INTO MOVIE VALUE('OM SHANTHI OM','SHARUK KHAN','HINDI',2007,6.7,'FARAH KHAN','60 CRORES','MELODRAMA','GOOD','AMAZON');

CREATE TABLE RESTAURANTS(
NAME VARCHAR(25),
RATINGS FLOAT,
ADDRESS VARCHAR(25),
OPENS VARCHAR(25),
CLOSES VARCHAR(25),
CONTACT_NUMBER LONG,
PLACE VARCHAR(25),
TYPE_OF_RESTURANTS VARCHAR(25),
REVIEWS VARCHAR(25),
HOLIDAY VARCHAR(25)
);

SELECT*FROM RESTAURANTS;
INSERT INTO RESTAURANTS VALUE('PALGUNI',7.5,'RING ROAD','6 AM','11 PM',9271615452,'HASSAN','VEG','GOOD','SUNDAY');
INSERT INTO RESTAURANTS VALUE('KRISHNA',8.1,'YASHVANTHPUR','5AM','12 PM',927192628,'BANGLORE','N0N VEG','VERY GOOD','SUNDAY');
INSERT INTO RESTAURANTS VALUE('RAMA',9.0,'VIJAYA NAGAR','6 AM','11 PM',9271615452,'HASSAN','NON VEG','GOOD','MONDAY');
INSERT INTO RESTAURANTS VALUE('RANI',7.9,'RAJAJI NAGAR','6 AM','10 PM',9271694452,'TUMKUR','VEG','SUPER','SUNDAY');
INSERT INTO RESTAURANTS VALUE('PARVATHI',6.9,'NAGSANDRA','7 AM','11 PM',9741615452,'BANGLORE','NON VEG','GOOD','TUESDAY');
INSERT INTO RESTAURANTS VALUE('RESTO BAR',6.9,'INDRA NAGAR','5 AM','12 PM',9296415452,'DAVENGERE','VEG','EXCELLENT','SUNDAY');
INSERT INTO RESTAURANTS VALUE('KALPATHARU',5.9,'SRIRAMPURA','9 AM','11 PM',927752452,'HAVERI','VEG','GOOD','SUNDAY');
INSERT INTO RESTAURANTS VALUE('SHI KRISHNA',8.6,'MAIN ROAD','6 AM','10:30 PM',906543252,'CHIKKAMAGALURU','NON VEG','GOOD','THURSDAY');
INSERT INTO RESTAURANTS VALUE('MAVITHA',6.0,'JAYA NAGAR','8 AM','11 PM',9279754352,'BANGLORE','VEG','VERY GOOD','SUNDAY');

CREATE TABLE MALLS(
NAME_OF_MALL VARCHAR(20),
PLACE VARCHAR(20),
NUMBER_OF_FLOORS INT,
NUMBER_OF_SHOPS INT,
EMPLOYEE INT,
MAINTENANCE_STAFF_NUM INT,
NUMBER_OF_AC INT,
NUMBER_OF_ESCALATOR INT,
OPEN_TIME VARCHAR(10),
CLOSE_TIME VARCHAR(10)
);

SELECT * FROM MALLS;
INSERT INTO MALLS VALUE('ORION MALL','BANGLORE',10,100,500,90,140,30,'9 AM','10 PM');
INSERT INTO MALLS VALUE('ELEMENT MALL','BANGLORE',6,150,550,100,160,50,'9 AM','10 PM');
INSERT INTO MALLS VALUE('LULU MALL','BANGLORE',8,120,510,70,180,30,'9 AM','10 PM');
INSERT INTO MALLS VALUE('FORUM MALL','BANGLORE',10,110,800,100,120,40,'9 AM','10 PM');
INSERT INTO MALLS VALUE('MANTRI SQUARE MALL','BANGLORE',9,115,600,90,160,25,'9 AM','10 PM');
INSERT INTO MALLS VALUE('GOPALAN MALL','BANGLORE',8,110,640,100,150,60,'9 AM','10 PM');
INSERT INTO MALLS VALUE('UB CITY','BANGLORE',10,160,250,120,130,45,'9 AM','10 PM');
INSERT INTO MALLS VALUE('GT WORLD MALL','BANGLORE',8,100,450,80,180,35,'9 AM','10 PM');
INSERT INTO MALLS VALUE('PARK SQUARE MALL','BANGLORE',13,110,580,110,150,68,'9 AM','10 PM');
INSERT INTO MALLS VALUE('1MG - LIDO MALL','BANGLORE',10,100,560,100,130,64,'9 AM','10 PM');

CREATE TABLE RESORT(
NAME_OF_RESORT VARCHAR(25),
PLACE VARCHAR(25),
RATING FLOAT,
NUMBER_OF_GAMES INT,
NUMBER_OF_ROOMS INT,
COST_TO_STAY INT,
COST_WITHOUT_STAY INT,
FOOD VARCHAR(25),
RESORT_OPENS_TIME VARCHAR(10),
RESORT_CLOSES_AT VARCHAR(20)
);

SELECT * FROM RESORT;
INSERT INTO RESORT VALUE('OCTAVE CASTLE SUITES','BANGLORE',4.3,20,30,2520,1500,'VEG','6AM','10PM');
INSERT INTO RESORT VALUE('GRAND MERCURE','BANGLORE',4.5,25,35,3000,1800,'VEG AND NON VEG','6AM','10PM');
INSERT INTO RESORT VALUE('HOTEL ROYAL ORCHID','BANGLORE',4.2,22,38,2440,1540,'VEG','7AM','10PM');
INSERT INTO RESORT VALUE('WINDFLOWER PRAKRUTHI','BANGLORE',4.4,28,45,2517,1080,'VEG','6AM','10PM');
INSERT INTO RESORT VALUE('ROYAL ORCHID','BANGLORE',4.3,29,33,2643,1800,'VEG','6AM','10PM');
INSERT INTO RESORT VALUE('ALOFT BENGALURU','BANGLORE',4.3,21,38,3500,2500,'NON VEG','7AM','10PM');
INSERT INTO RESORT VALUE('ZURI WHITEFIELD','BANGLORE',3.9,30,39,2956,1500,'VEG','6AM','10PM');
INSERT INTO RESORT VALUE('BLOOMROOMS','BANGLORE',3.4,35,44,3500,2710,'VEG AND NON VEG','6AM','10PM');
INSERT INTO RESORT VALUE('DAYS SUITES','BANGLORE',4.3,25,43,4000,2900,'VEG','6AM','10PM');

CREATE TABLE SHOWROOMS(
NAME VARCHAR(25),
PLACE VARCHAR(25),
RATNG INT,
OPEN_TIME VARCHAR(10),
CLOSE_TIME VARCHAR(10),
HOLIDAY VARCHAR(10),
TYPE_OF_SHOWROOM VARCHAR(20),
EMPLOYEES_NUM INT,
MAIN_BRANCH VARCHAR(20),
BUILDING_FLOORS INT
);

SELECT * FROM SHOWROOMS;
INSERT INTO SHOWROOMS VALUE('ADVAITH KIA','BANGLORE',4.3,'9AM','9PM','SUNDAY','CAR',40,'DELHI',4);
INSERT INTO SHOWROOMS VALUE('MARUTHI SUZUKI','BANGLORE',4.4,'9AM','10PM','SUNDAY','CAR',60,'CHENNAI',3);
INSERT INTO SHOWROOMS VALUE('NEXA','BANGLORE',4.2,'9AM','9PM','SUNDAY','CAR',30,'DELHI',4);
INSERT INTO SHOWROOMS VALUE('SILICON HONDA','BANGLORE',4.3,'9AM','10PM','SUNDAY','CAR',50,'DELHI',2);
INSERT INTO SHOWROOMS VALUE('TANDAVA ARTS','BANGLORE',4.0,'9AM','9PM','SUNDAY','PLATES',45,'DELHI',5);
INSERT INTO SHOWROOMS VALUE('ROYAL ENFIELD','BANGLORE',3.9,'10AM','9PM','SUNDAY','BIKE',65,'CHENNAI',3);
INSERT INTO SHOWROOMS VALUE('TATA SHOWROOM','BANGLORE',4.4,'9AM','9PM','SUNDAY','CAR',80,'DELHI',4);
INSERT INTO SHOWROOMS VALUE('MG MOTOR INDIA','BANGLORE',4.2,'9AM','10PM','SUNDAY','CAR',55,'DELHI',2);
INSERT INTO SHOWROOMS VALUE('YAMAHA MOTOR','BANGLORE',4.1,'10AM','9PM','SUNDAY','BIKES',60,'CHENNAI',3);
INSERT INTO SHOWROOMS VALUE('BATA SHOWROOM','BANGLORE',3.9,'9AM','9PM','SUNDAY','SHOE STORE',50,'DELHI',3);

ALTER TABLE RESORT RENAME RESORT_BANGLORE;
ALTER TABLE SHOWROOMS ADD COLUMN SHOWROOM_ID INT;
ALTER TABLE RESTAURANTS RENAME COLUMN RATINGS TO RATING ;
ALTER TABLE MALLS DROP COLUMN EMPLOYEE;
DROP TABLE MALLS;
ALTER TABLE METRO MODIFY COLUMN number_of_tracks LONG;



















































































